homeassistant:
  # Name of the location where Home Assistant is running
  name: Our House

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elv

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_tz

  # Customization file
  customize: !include customize.yaml
  # Packages
  packages: !include_dir_named packages

# System Health component
system_health:

alarm_control_panel: !include alarm_config.yaml

# Lovelace YAML mode
lovelace:
  mode: yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# HACS (community store)
hacs:
  token: !secret hacs_key
  appdaemon: false
  python_script: false
  theme: true

# Discover some devices automatically
discovery:
  enable:

# Speedtest component
speedtestdotnet:
  server_id: 4297

recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret db_url
  exclude:
    domains:
      - alert
      - automation
      - sun
      - seasons
      - input_number
      - input_boolean
      - zone
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_high_temperature_2
      - sensor.dark_sky_daily_high_temperature_3
      - sensor.dark_sky_daily_high_temperature_4
      - sensor.dark_sky_daily_high_temperature_5
      - sensor.dark_sky_daily_high_temperature_6
      - sensor.dark_sky_daily_high_temperature_7
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_daily_low_temperature_2
      - sensor.dark_sky_daily_low_temperature_3
      - sensor.dark_sky_daily_low_temperature_4
      - sensor.dark_sky_daily_low_temperature_5
      - sensor.dark_sky_daily_low_temperature_6
      - sensor.dark_sky_daily_low_temperature_7
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_humidity_2
      - sensor.dark_sky_humidity_3
      - sensor.dark_sky_humidity_4
      - sensor.dark_sky_humidity_5
      - sensor.dark_sky_humidity_6
      - sensor.dark_sky_humidity_7
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_1
      - sensor.dark_sky_icon_2
      - sensor.dark_sky_icon_3
      - sensor.dark_sky_icon_4
      - sensor.dark_sky_icon_5
      - sensor.dark_sky_icon_6
      - sensor.dark_sky_icon_7
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_1
      - sensor.dark_sky_precip_2
      - sensor.dark_sky_precip_3
      - sensor.dark_sky_precip_4
      - sensor.dark_sky_precip_5
      - sensor.dark_sky_precip_6
      - sensor.dark_sky_precip_7
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_1
      - sensor.dark_sky_precip_intensity_2
      - sensor.dark_sky_precip_intensity_3
      - sensor.dark_sky_precip_intensity_4
      - sensor.dark_sky_precip_intensity_5
      - sensor.dark_sky_precip_intensity_6
      - sensor.dark_sky_precip_intensity_7
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_probability_4
      - sensor.dark_sky_precip_probability_5
      - sensor.dark_sky_precip_probability_6
      - sensor.dark_sky_precip_probability_7
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_1
      - sensor.dark_sky_pressure_2
      - sensor.dark_sky_pressure_3
      - sensor.dark_sky_pressure_4
      - sensor.dark_sky_pressure_5
      - sensor.dark_sky_pressure_6
      - sensor.dark_sky_pressure_7
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_1
      - sensor.dark_sky_wind_bearing_2
      - sensor.dark_sky_wind_bearing_3
      - sensor.dark_sky_wind_bearing_4
      - sensor.dark_sky_wind_bearing_5
      - sensor.dark_sky_wind_bearing_6
      - sensor.dark_sky_wind_bearing_7
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_1
      - sensor.dark_sky_wind_speed_2
      - sensor.dark_sky_wind_speed_3
      - sensor.dark_sky_wind_speed_4
      - sensor.dark_sky_wind_speed_5
      - sensor.dark_sky_wind_speed_6
      - sensor.dark_sky_wind_speed_7
      - sensor.season
      - sensor.time
      - sensor.weekday
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

http: !include http.yaml

# Enables a map showing the location of tracked devices
#map:

upnp:

# Track the sun
sun:
  monitored_conditions:
    - max_elevation
    - elevation
    - sunrise
    - sunset
  # scan_interval:
  #   minutes: 10

# Add Configurator to sidebar
panel_iframe: !include panel_iframe.yaml

# Device Home/Away Tracking
device_tracker: !include device_tracker.yaml

# Homekit support
homekit: !include homekit.yaml

# Hive Control
hive:
  username: !secret hive_un
  password: !secret hive_pass

# Nest Integration
nest:
  client_id: !secret nest_un
  client_secret: !secret nest_pw

# Plex Control
media_player: !include media-player.yaml

# Apple TV Support
apple_tv:
  # - host: 192.168.1.128
  #   login_id: 00000000-0aa4-392d-8570-094646234f09
  #   name: Living Room
  #   start_off: START_OFF_1
  #   credentials: C7D78938FCA90788:FA67F149D480BD8247379054AB77A2C0A1474F49D0820CE9FC3310B000EA5AE9

# Sensors
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

# Transmission Sensor
transmission:
  host: !secret fsrv_ip
  scan_interval: 5
  turtle_mode: true
  monitored_conditions:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'
    - 'started_torrents'
    - 'completed_torrents'

telegram_bot:
  - platform: polling
    api_key: !secret tbot_key
    allowed_chat_ids:
      - !secret tbot_kid
      # - !secret tbot_tid

notify:
  - name: hassbot
    platform: telegram
    chat_id: !secret tbot_kid

# Cameras
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# camera: !include_dir_list camera/

# Octoprint
# octoprint:
#   host: 192.168.1.9
#   api_key: !secret octo_key
#   bed: true
#   number_of_tools: 1

# Google Calendar support
google:
  client_id: !secret gcal_id
  client_secret: !secret gcal_sec

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# Groups
group: !include groups.yaml
# Automations
automation: !include automations.yaml
# Scripts
script: !include scripts.yaml
