# - platform: alexa
#   email: !secret amzn_un
#   password: !secret amzn_pw
#   url: "amazon.ca"

- platform: spotify
  client_id: !secret spot_un
  client_secret: !secret spot_pw

- platform: plex
  entity_namespace: 'plex'
  scan_interval: 5
  show_all_controls: false
  use_episode_art: true
  remove_unavailable_clients: true
  client_remove_interval: 600

